// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///flutter pub add flutter_map
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
    return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh1VHVfpCCy-C0HMJopFCnWb3GYYWecZY',
    appId: '1:260428473003:android:008ee1fc750489b85d8dee',
    messagingSenderId: '260428473003',
    projectId: 'geoquest-4b7e1',
    storageBucket: 'geoquest-4b7e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUKbA0_kVJ_POWh4Ah0gl_4au_lPaC3I0',
    appId: '1:260428473003:ios:75e63ea37c4f87295d8dee',
    messagingSenderId: '260428473003',
    projectId: 'geoquest-4b7e1',
    storageBucket: 'geoquest-4b7e1.firebasestorage.app',
    iosBundleId: 'htl.le.application',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkGB5Iqz3zyZN7jKBRMX9TuMFZPQsgNnM',
    appId: '1:260428473003:web:dd6226542fbad3505d8dee',
    messagingSenderId: '260428473003',
    projectId: 'geoquest-4b7e1',
    authDomain: 'geoquest-4b7e1.firebaseapp.com',
    storageBucket: 'geoquest-4b7e1.firebasestorage.app',
    measurementId: 'G-ZHX29J6TDB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUKbA0_kVJ_POWh4Ah0gl_4au_lPaC3I0',
    appId: '1:260428473003:ios:75e63ea37c4f87295d8dee',
    messagingSenderId: '260428473003',
    projectId: 'geoquest-4b7e1',
    storageBucket: 'geoquest-4b7e1.firebasestorage.app',
    iosBundleId: 'htl.le.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkGB5Iqz3zyZN7jKBRMX9TuMFZPQsgNnM',
    appId: '1:260428473003:web:f0d6fb966684f1365d8dee',
    messagingSenderId: '260428473003',
    projectId: 'geoquest-4b7e1',
    authDomain: 'geoquest-4b7e1.firebaseapp.com',
    storageBucket: 'geoquest-4b7e1.firebasestorage.app',
    measurementId: 'G-VLQ7JS4HNE',
  );

}